apiVersion: v1
kind: Service
metadata:
 creationTimestamp: null
 labels:
  app: redis-test
 name: redis-test
spec:
 ports:
 - port: 6379
   protocol: TCP
   targetPort: 6379
 selector:
   app: redis-test
status:
 loadBalancer: {}
